---
title: "Pear Deck"
output:
  html_document:
    df_print: paged
---

```{r}
#####################
# SETUP STEPS
#####################

# Clear environment
rm(list=ls()) 

# Capture start time
code_start_time <- Sys.time()

# Install packages (if needed)
#install.packages("zoo")

# Load libraries
library(bigrquery)
library(reshape2)
library(ggplot2)
library(tidyverse)
library(scales)
library(zoo)

# Set working directory
setwd("C:\\Users\\katie\\Dropbox\\Grad School - Business Analytics Masters Program\\2019 Fall Classes\\Pear Deck - Analytics Experience\\R Scripts")

# Data pull setup
project_id <- "peardeck-external-projects"

# Set upper limit date to included usage data 
upper_limit_date <- "2019-10-31"

#####################
# SETUP NOTES
#####################

# Website on how to connect to Google BigQuery in R: https://www.blendo.co/blog/access-data-google-bigquery-python-r/
# https://www.rdocumentation.org/packages/bigrquery/versions/1.2.0/topics/bq_query

# https://www.datacamp.com/community/tutorials/long-wide-data-R

# install.packages("bigrquery")
# install.packages("DescTools")
```

```{r}
#####################
# DATA PULL: User Statuses
#####################

# 10 seconds
sql_string <- "SELECT CAST(externalid as STRING), first_pres_after_trial, last_pres_1st_few_mnths, timestamp, 
CASE WHEN first_pres_after_trial = timestamp THEN b.account_status END AS account_status_min,
CASE WHEN last_pres_1st_few_mnths = timestamp THEN b.account_status END AS account_status_max

FROM `peardeck-external-projects.buisness_analytics_in_practice_project.gslides_addon_launch_presentation` b
RIGHT JOIN

(
SELECT externalid, MIN(timestamp) as first_pres_after_trial, MAX(timestamp) as last_pres_1st_few_mnths
FROM `peardeck-external-projects.buisness_analytics_in_practice_project.gslides_addon_launch_presentation` lp_i RIGHT JOIN `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` uf ON lp_i.user_id = uf.externalid
WHERE ((DATE(timestamp) BETWEEN DATE_ADD(DATE(FirstSeen), INTERVAL 1 MONTH) AND DATE_ADD(DATE(FirstSeen), INTERVAL 3 MONTH)) OR timestamp IS NULL) 
AND (DATE(FirstSeen) BETWEEN '2018-08-05' AND '2018-08-18')
GROUP BY externalid
) a

ON b.user_id = a.externalid AND (b.timestamp = a.first_pres_after_trial OR b.timestamp = a.last_pres_1st_few_mnths)
--Note: count does not exactly equal what's in user facts if user hasn't launched a presentation ever."

query_start_time <- Sys.time()
df_us <- query_exec(sql_string, project = project_id, use_legacy_sql = FALSE, max_pages = Inf) #, allowLargeResults = TRUE
query_end_time <- Sys.time()
query_runtime <- query_end_time - query_start_time
print(round(query_runtime,1))

```

```{r}
#####################
# DATA PULL: slide_presented & student_responses
#####################

# NEWEST VERSION
sql_string <- "SELECT 
CAST(sp.externalid AS STRING) AS teacher,
DATE(sp.timestamp) AS Date,
EXTRACT(HOUR FROM sp.timestamp) AS hour,
COUNT(DISTINCT sp.presentation_id) as num_presentations,
COUNT(DISTINCT sr.student) as num_students

FROM 

(SELECT externalid, presentation_id, slide_id, timestamp, DATE(timestamp) as date, EXTRACT(HOUR FROM timestamp) as hour
FROM `peardeck-external-projects.buisness_analytics_in_practice_project.slide_presented` sp_i RIGHT JOIN `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` uf_i 
ON sp_i.user_id = uf_i.externalid
WHERE 
((DATE(timestamp) BETWEEN DATE(FirstSeen) AND DATE_ADD(DATE(FirstSeen), INTERVAL 3 MONTH)) 
OR (DATE(timestamp) BETWEEN DATE_ADD(DATE(FirstSeen), INTERVAL 1 YEAR) AND DATE_ADD(DATE_ADD(DATE(FirstSeen), INTERVAL 3 MONTH), INTERVAL 1 YEAR) 
OR timestamp IS NULL))
AND (DATE(FirstSeen) BETWEEN '2018-08-05' AND '2018-08-18') 
) sp 

LEFT JOIN 

(SELECT externalid, teacher, student, presentation, timestamp, slide, DATE(timestamp) as date, EXTRACT(HOUR FROM timestamp) as hour
FROM `peardeck-external-projects.buisness_analytics_in_practice_project.student_responses` sr_i RIGHT JOIN `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` uf_i 
ON sr_i.teacher = uf_i.externalid
WHERE app not like '%flash%' 
AND ((DATE(timestamp) BETWEEN DATE(FirstSeen) AND DATE_ADD(DATE(FirstSeen), INTERVAL 3 MONTH)) 
OR (DATE(timestamp) BETWEEN DATE_ADD(DATE(FirstSeen), INTERVAL 1 YEAR) AND DATE_ADD(DATE_ADD(DATE(FirstSeen), INTERVAL 3 MONTH), INTERVAL 1 YEAR) 
OR timestamp IS NULL))
AND (DATE(FirstSeen) BETWEEN '2018-08-05' AND '2018-08-18')
) sr 

ON sp.externalid = sr.externalid AND sp.slide_id = sr.slide AND sp.presentation_id = sr.presentation AND sp.date = sr.date AND sp.hour = sr.hour

GROUP BY sp.externalid, DATE(sp.timestamp), EXTRACT(HOUR FROM sp.timestamp)
--Note: count does not exactly equal what's in user facts if user hasn't launched a presentation ever.
"

# NOTE: version below joins student_responses & slide_presented (which includes slides not presented to an audience)
# sql_string <- "SELECT 
# CAST(user_id AS STRING) AS teacher,
# DATE(sp.timestamp) AS Date,
# EXTRACT(HOUR FROM sp.timestamp) AS hour,
# COUNT(DISTINCT sp.presentation_id) as num_presentations,
# COUNT(DISTINCT sr.student) as num_students
# 
# FROM 
# 
# (SELECT *, DATE(timestamp) as date, EXTRACT(HOUR FROM timestamp) as hour
# FROM `peardeck-external-projects.buisness_analytics_in_practice_project.slide_presented`
# WHERE DATE(timestamp) >= '2018-01-01' AND DATE(timestamp) <= '2019-10-31' AND user_id NOT IN (
# (SELECT externalid FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` WHERE DATE(firstseen) >= '2019-10-01')
# )) sp 
# 
# LEFT JOIN 
# 
# (SELECT *, DATE(timestamp) as date, EXTRACT(HOUR FROM timestamp) as hour
# FROM `peardeck-external-projects.buisness_analytics_in_practice_project.student_responses`
# WHERE app not like '%flash%' AND DATE(timestamp) >= '2018-01-01' AND DATE(timestamp) <= '2019-10-31' AND teacher NOT IN (
# (SELECT externalid FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` WHERE DATE(firstseen) >= '2019-10-01')
# )) sr 
# 
# ON sp.slide_id = sr.slide AND sp.presentation_id = sr.presentation AND sp.date = sr.date AND sp.hour = sr.hour
# 
# GROUP BY user_id, DATE(sp.timestamp), EXTRACT(HOUR FROM sp.timestamp)"

# NOTE: version below is student_responses table only.
#sql_string <- "SELECT CAST(teacher AS STRING) AS teacher, DATE(timestamp) AS Date, EXTRACT(HOUR FROM timestamp) AS hour, COUNT(DISTINCT presentation) AS num_presentations, COUNT(DISTINCT student) as num_students FROM `peardeck-external-projects.buisness_analytics_in_practice_project.student_responses` WHERE lower(app) not like '%flash%' AND DATE(timestamp) >= '2017-01-01' AND DATE(timestamp) <= '2019-10-31' AND teacher NOT IN ((SELECT externalid FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` WHERE DATE(firstseen) >= '2019-10-01')) GROUP BY teacher, DATE(timestamp), EXTRACT(HOUR FROM timestamp)"

# Note: structured the query this way because slide_id can be null

# Pull data
# Approximate run time: 7.3 min
query_start_time <- Sys.time()
df_sr <- query_exec(sql_string, project = project_id, use_legacy_sql = FALSE, max_pages = Inf) #, allowLargeResults = TRUE
query_end_time <- Sys.time()
query_runtime <- query_end_time - query_start_time
print(round(query_runtime,1))

# Add field of date in YYYY-MM format
df_sr$Date_year_month <- format(df_sr$Date, format="%Y-%m")

```

```{r}
#####################
# DATA PULL: slide_presented
#####################

# NEVERMIND DON'T USE

# sql_string <- "SELECT user_id, slide_type, SUM(slide_type_ct) AS slide_type_ct FROM (SELECT CAST(user_id AS STRING) AS user_id, presentation_id, slide_id, slide_type, DATE(timestamp) as Date, EXTRACT(HOUR FROM timestamp) as Hour, COUNT(DISTINCT user_id) AS slide_type_ct FROM `peardeck-external-projects.buisness_analytics_in_practice_project.slide_presented` WHERE DATE(timestamp) >= '2017-01-01' AND DATE(timestamp) <= '2019-10-31' AND user_id NOT IN ((SELECT externalid FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` WHERE DATE(firstseen) >= '2019-10-01')) GROUP BY user_id, presentation_id, slide_id, slide_type, DATE(timestamp), EXTRACT(HOUR FROM timestamp)) GROUP BY user_id, slide_type"
# 
# # Pull data
# # Run time: 3 min
# query_start_time <- Sys.time()
# df_sp <- query_exec(sql_string, project = project_id, use_legacy_sql = FALSE, max_pages = Inf)
# query_end_time <- Sys.time()
# query_runtime <- query_end_time - query_start_time
# print(round(query_runtime,1))
# 
# names(df_sp)[names(df_sp) == "user_id"] <- "teacher"

```


```{r}
#####################
# DATA PULL: user_facts_anonymized
#####################

# NEW VERSION
sql_string <- "SELECT CAST(externalid AS STRING) as teacher, firstseen
FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` 
WHERE (DATE(FirstSeen) BETWEEN '2018-08-05' AND '2018-08-18')"
  
# sql_string <- "SELECT DISTINCT CAST(externalid AS STRING) AS externalid, profile_role, firstseen, CAST(domain AS STRING) as domain, firstpremiumtime, premiumstatusatsignup, accountType, expirationdate, trial_end, coupon_medium FROM `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized` JOIN `peardeck-external-projects.buisness_analytics_in_practice_project.student_responses` ON `peardeck-external-projects.buisness_analytics_in_practice_project.user_facts_anonymized`.externalid = `peardeck-external-projects.buisness_analytics_in_practice_project.student_responses`.teacher WHERE DATE(firstseen) < '2019-10-01' AND lower(app) not like '%flash%' AND DATE(timestamp) >= '2017-01-01' AND DATE(timestamp) <= '2019-10-31'"

# Pull data
# Run time: 1 min
query_start_time <- Sys.time()
df_uf <- query_exec(sql_string, project = project_id, use_legacy_sql = FALSE, max_pages = Inf)
query_end_time <- Sys.time()
query_runtime <- query_end_time - query_start_time
print(round(query_runtime,1))

```

```{r}
#####################
# CREATE DFs: df_sr_wide & df_sr_long
#####################

### Presentations for year/month

# Create summary: presentations by year/month
df_sr <- group_by(df_sr, teacher, Date_year_month)
summ  <- summarize(df_sr, num_presentations = sum(num_presentations)) 
df_sr <- ungroup(df_sr)

# Create wide df
df_sr_wide <- dcast(summ, teacher ~ Date_year_month, value.var="num_presentations")

# Create new col in df_sr_wide: total_presentations & total_months_used
summ <- group_by(summ, teacher)
summ2 <- summarize(summ, num_presentations = sum(num_presentations)) 
summ3 <- summarize(summ, total_months_used = n()) 
summ <- ungroup(summ)

# df_sr_wide: Set NAs to 0 (important for calculation of average and SD later)
df_sr_wide[is.na(df_sr_wide)] <- 0 

# Create df_sr_long of presentations by year/month (for summaries later)
df_sr_long <- melt(df_sr_wide[,1:(ncol(df_sr_wide))], measure.vars = 2:(ncol(df_sr_wide)))
colnames(df_sr_long)[2] = "Date_year_month"
colnames(df_sr_long)[3] = "num_presentations"

### Add to df_sr_wide: # Presentations by user & Total Months by user
df_sr_wide$total_presentations <- summ2$num_presentations
df_sr_wide$total_months_used <- summ3$total_months_used

### Student Engagement

# Create bucket labels for num_students
df_sr$num_students_label <- df_sr$num_students
df_sr$num_students_label[which(df_sr$num_students == 1)] <- "0_Testing"
df_sr$num_students_label[which(df_sr$num_students >= 2 & df_sr$num_students <= 5)] <- "1_Low"
df_sr$num_students_label[which(df_sr$num_students >= 6 & df_sr$num_students <= 10)] <- "2_Low-Medium"
df_sr$num_students_label[which(df_sr$num_students >= 11 & df_sr$num_students <= 30)] <- "3_Medium"
df_sr$num_students_label[which(df_sr$num_students >= 31 & df_sr$num_students <= 40)] <- "4_Medium-High"
df_sr$num_students_label[which(df_sr$num_students >= 41)] <- "5_High"

# Rename the levels (note: did it this way to preserve the desired order)
df_sr$num_students_label <- factor(df_sr$num_students_label)
levels(df_sr$num_students_label) <- paste("Num_stu_", substr(levels(df_sr$num_students_label), 3, nchar(levels(df_sr$num_students_label))), sep="")

# Create summary: Count in each student engagement bucket by user
df_sr <- group_by(df_sr, teacher, num_students_label)
summ  <- summarize(df_sr, num_students_label_ct = n()) 
df_sr <- ungroup(df_sr)
# Merge in total_presentations
summ <- merge(summ, df_sr_wide[,c(which(colnames(df_sr_wide)=="teacher"),which(colnames(df_sr_wide)=="total_presentations"))])
# Calculate normalized num_students_label
summ$num_stu_norm <- round(summ$num_students_label_ct/summ$total_presentations,2)
# Make it wide (merge prep)
summ2 <- dcast(summ, teacher ~ num_students_label, value.var="num_stu_norm")
summ2[is.na(summ2)] <- 0 
# Add to df_sr_wide
df_sr_wide <- merge(df_sr_wide, summ2, all = FALSE)

# Add Date_year_month_2 to df_sr
df_sr$Date_year_month_2 <- as.Date(paste(df_sr$Date_year_month, "-01", sep=""))

# Create summary: review first and last use dates
df_sr <- group_by(df_sr, teacher)
summ  <- summarize(df_sr, YM_first_use = min(Date_year_month_2), YM_last_use = max(Date_year_month_2)) 
df_sr <- ungroup(df_sr)
summ$months_bw_1st_last_use <- ((as.yearmon(strptime(summ$YM_last_use, format = "%Y-%m-%d")) - as.yearmon(strptime(summ$YM_first_use, format = "%Y-%m-%d")))*12)+1

# Add to df_sr_wide
df_sr_wide <- merge(df_sr_wide, summ, all = FALSE)

# Add months_since_1st_use to df_sr_wide
df_sr_wide$months_since_1st_use <- ((as.yearmon(strptime(upper_limit_date, format = "%Y-%m-%d")) - as.yearmon(strptime(df_sr_wide$YM_first_use, format = "%Y-%m-%d")))*12)+1

# Add normalized time usage to df_sr_wide
df_sr_wide$time_usage_perc <- round(df_sr_wide$total_months_used/df_sr_wide$months_since_1st_use,2)
#df_sr_wide$time_usage_perc2 <- round(df_sr_wide$total_months_used/df_sr_wide$months_bw_1st_last_use,2)

# Add normalized presentation usage to df_sr_wide
df_sr_wide$pres_usage_norm1 <- round(df_sr_wide$total_presentations/df_sr_wide$total_months_used,2)
df_sr_wide$pres_usage_norm2 <- round(df_sr_wide$total_presentations/df_sr_wide$months_bw_1st_last_use,2)
df_sr_wide$pres_usage_norm3 <- round(df_sr_wide$total_presentations/df_sr_wide$months_since_1st_use,2)

# Remove unnecessary dfs
rm(list = c("summ","summ2","summ3"))
```

```{r}
#####################
# CREATE DFs: df_sp_wide
#####################

# Create summary: total slides per teacher
df_sp <- group_by(df_sp, teacher)
summ <- summarize(df_sp, total_slides = sum(slide_type_ct))
df_sp <-ungroup(df_sp)

# Merge total_slides into df_sp
df_sp <- merge(summ, df_sp)
  
# Calculate normalized slide_type
df_sp$slide_type_amt_norm <- round(df_sp$slide_type_ct/df_sp$total_slides, 2)

# Create df_sp_wide
df_sp_wide <- dcast(df_sp, teacher + total_slides ~  slide_type, value.var = "slide_type_amt_norm")

```

```{r}
#####################
# EXAMINE / REMOVE LOW # STUDENT ENGAGEMENTS
# * OPTIONAL *
#####################

# Copy original into new df
df_sr_original <- df_sr

# Copy into new df
df_sr_lowstu <- df_sr

# Capture the unique number of teachers in the data set BEFORE excluding low student engagements
num_teachers_orig <- length(levels(factor(df_sr_lowstu$teacher)))

# Set theshold # (of student engagements to exclude - number is inclusive)
low_num_exclude <- 1

df_sr_lowstu <- df_sr_lowstu[-(which(df_sr_lowstu$num_students <= 1)), ]

# Capture the unique number of teachers in the data set AFTER excluding low student engagements
num_teachers_after <- length(levels(factor(df_sr_lowstu$teacher)))

# Print message about the number of teachers removed from data set
print(paste(num_teachers_orig - num_teachers_after, "teachers removed from data set because their only use of the product involved", low_num_exclude, "or fewer students."))

# # Replace df_sr with version without low student engagements
# df_sr <- df_sr_lowstu
# 
# # Replace df_sr with version with low student engagements
# df_sr <- df_sr_original


# Rename the levels (for a pretty plot)
levels(df_sr$num_students_label) <- substr(levels(df_sr$num_students_label), 9, nchar(levels(df_sr$num_students_label)))

# Create summary of num_students_label
df_sr <- group_by(df_sr, num_students_label)
summ_num_stu <- summarize(df_sr, total = n())
df_sr <- ungroup(df_sr)

# 
num_bins <- 1
breaks <- num_bins*(0:(60/num_bins))

p <- 
  ggplot(data=summ_num_stu, aes(x=num_students_label, y=total)) + #, binwidth = num_bins
  geom_bar(stat = "identity") +
  scale_y_continuous(name = "Count", labels = scales::comma) +  # unit_format(unit = "K") +
  scale_x_discrete(name="Number of Students") +
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Student Engagement Distribution") + 
  theme(text = element_text(size = 14)) 
print(p)
ggsave(filename = "Student Engagement Distribution.png", plot = p, width = 15, height = 7, units = "in") 

# Rename the levels back to what they were
levels(df_sr$num_students_label) <- paste("Num_stu_", levels(df_sr$num_students_label), sep="")

```


```{r, fig.width=20,fig.height=7}
#####################
# EXPLORE: usage over time USING LONG VERSION (includes num_presentations = 0)
#####################

# Create usage summary by Year/Month
df_sr_long$Date_year_month_2 <- as.Date(paste(df_sr_long$Date_year_month, "-01", sep=""))

df_sr_long <- group_by(df_sr_long, Date_year_month_2, teacher)
summ_vIn0_yearmonth_teacher <- summarize(df_sr_long, total_pres = sum(num_presentations))
df_sr_long <- ungroup(df_sr_long)

summ_vIn0_yearmonth_teacher <- group_by(summ_vIn0_yearmonth_teacher, Date_year_month_2)
summ_vIn0_yearmonth <- summarize(summ_vIn0_yearmonth_teacher, total_presentations = sum(total_pres), total_presentations_avg = round(mean(total_pres),0), total_presentations_sd = round(sd(total_pres),1))
summ_vIn0_yearmonth_teacher <- ungroup(summ_vIn0_yearmonth_teacher)


# By Month: count

p <- ggplot(data=summ_vIn0_yearmonth, aes(x=Date_year_month_2, y=total_presentations)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Total Presentations", labels = scales::comma) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_count_bar(vIn0).png", plot = p, width = 20, height = 7, units = "in")

# By Month: average

p <- ggplot(data=summ_vIn0_yearmonth, aes(x=Date_year_month_2, y=total_presentations_avg)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Average Total Presentations", labels = scales::comma, breaks = 0:(max(summ_vIn0_yearmonth$total_presentations_avg))) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Average # Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_avg_bar(vIn0).png", plot = p, width = 20, height = 7, units = "in")


# By Month: standard deviation

p <- ggplot(data=summ_vIn0_yearmonth, aes(x=Date_year_month_2, y=total_presentations_sd)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Total Presentations Standard Deviation", labels = scales::comma) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Standard Deviation # Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_sd_bar(vIn0).png", plot = p, width = 20, height = 7, units = "in")

# # By Week: count
# 
# # Scatter plot w/ trend line
# p <- ggplot(data=df_sr, aes(x=Date, y=num_presentations)) +
#   geom_point(stat="identity") + 
#   geom_smooth() +
#   scale_x_date(name = "Year/Week", date_breaks = "1 week", date_labels = "%Y-%m-%d") + 
#   theme(panel.grid.minor.y = element_blank()) +
#   theme(panel.background = element_blank()) +
#   ggtitle("Presentations by Week") +
#   theme(text = element_text(size = 14)) +
#   theme(axis.text.x = element_text(angle = 45))
# 
# ggsave(filename = "chart_byweek_scatter.png", plot = p, width = 85, height = 7, units = "in", limitsize = FALSE)

# # Line plot
# p <- ggplot(data=df_sr, aes(x=Date, y=num_presentations)) +
#   geom_line(stat="identity") +
#   scale_x_date(name = "Year/Week", date_breaks = "1 week", date_labels = "%Y-%m-%d") + 
#   theme(panel.grid.minor.y = element_blank()) +
#   theme(panel.background = element_blank()) +
#   ggtitle("Presentations by Week") +
#   theme(text = element_text(size = 14)) +
#   theme(axis.text.x = element_text(angle = 45))
# 
# ggsave(filename = "chart_byweek_line.png", plot = p, width = 85, height = 7, units = "in", limitsize = FALSE)
# 
# # By Week: average
# 
# #Add field of date in YYYY-WW format
# df_sr$Date_year_week <- as.numeric(format(df_sr$Date, format="%Y%V"))
# 
# #Add summary table NOTE: all 1s
# df_sr <- group_by(df_sr, Date_year_week)
# summ_by_Year_week <- summarize(df_sr, total_presentations_avg = round(mean(num_presentations),0), total_presentations_sd = round(sd(num_presentations),1))
# df_sr <- ungroup(df_sr)

```

```{r, fig.width=20,fig.height=7}
#####################
# EXPLORE: usage over time - EXCLUDES NUM_PRESENTATIONS = 0
#####################

# Create usage summary by Year/Month

df_sr <- group_by(df_sr, Date_year_month_2, teacher)
summ_vEx0_yearmonth_teacher <- summarize(df_sr, total_pres = sum(num_presentations))
df_sr <- ungroup(df_sr)

summ_vEx0_yearmonth_teacher <- group_by(summ_vEx0_yearmonth_teacher, Date_year_month_2)
summ_vEx0_yearmonth <- summarize(summ_vEx0_yearmonth_teacher, total_presentations = sum(total_pres), total_presentations_avg = round(mean(total_pres),0), total_presentations_sd = round(sd(total_pres),1))
summ_vEx0_yearmonth_teacher <- ungroup(summ_vEx0_yearmonth_teacher)


# By Month: count

p <- ggplot(data=summ_vEx0_yearmonth, aes(x=Date_year_month_2, y=total_presentations)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Total Presentations", labels = scales::comma) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_count_bar(vEx0).png", plot = p, width = 20, height = 7, units = "in")

# By Month: average

p <- ggplot(data=summ_vEx0_yearmonth, aes(x=Date_year_month_2, y=total_presentations_avg)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Average Total Presentations", labels = scales::comma) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Average # Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_avg_bar(vEx0).png", plot = p, width = 20, height = 7, units = "in")


# By Month: standard deviation

p <- ggplot(data=summ_vEx0_yearmonth, aes(x=Date_year_month_2, y=total_presentations_sd)) +
  geom_bar(stat="identity") + 
  scale_y_continuous(name = "Total Presentations Standard Deviation", labels = scales::comma) +  # unit_format(unit = "K")
  scale_x_date(name = "Year/Month", date_breaks = "1 month", date_labels = "%Y-%m") + 
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Standard Deviation # Presentations by Month") + 
  theme(text = element_text(size = 14)) + 
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_bymonth_sd_bar(vEx0).png", plot = p, width = 20, height = 7, units = "in")

# By Week: count

# Scatter plot w/ trend line
p <- ggplot(data=df_sr, aes(x=Date, y=num_presentations)) +
  geom_point(stat="identity") + 
  geom_smooth() +
  scale_x_date(name = "Year/Week", date_breaks = "1 week", date_labels = "%Y-%m-%d") + 
  theme(panel.grid.minor.y = element_blank()) +
  theme(panel.background = element_blank()) +
  ggtitle("Presentations by Week") +
  theme(text = element_text(size = 14)) +
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_byweek_scatter(vEx0).png", plot = p, width = 85, height = 7, units = "in", limitsize = FALSE)

# Line plot
p <- ggplot(data=df_sr, aes(x=Date, y=num_presentations)) +
  geom_line(stat="identity") +
  scale_x_date(name = "Year/Week", date_breaks = "1 week", date_labels = "%Y-%m-%d") + 
  theme(panel.grid.minor.y = element_blank()) +
  theme(panel.background = element_blank()) +
  ggtitle("Presentations by Week") +
  theme(text = element_text(size = 14)) +
  theme(axis.text.x = element_text(angle = 45))

ggsave(filename = "chart_byweek_line(vEx0).png", plot = p, width = 85, height = 7, units = "in", limitsize = FALSE)

# By Week: average

#Add field of date in YYYY-WW format
df_sr$Date_year_week <- as.numeric(format(df_sr$Date, format="%Y%V"))

#Add summary table NOTE: all 1s
df_sr <- group_by(df_sr, Date_year_week)
summ_vEx0_by_Year_week <- summarize(df_sr, total_presentations_avg = round(mean(num_presentations),0), total_presentations_sd = round(sd(num_presentations),1))
df_sr <- ungroup(df_sr)

```


```{r}
#####################
# EXPLORE: Number of students for a presentation
#####################

num_bins <- 1
breaks <- num_bins*(0:(60/num_bins))

p <- 
  qplot(df_sr$num_students, geom="histogram", binwidth = num_bins) +
  scale_y_continuous(name = "Count", labels = scales::comma) +  # unit_format(unit = "K") +
  scale_x_continuous(name="Number of Students", breaks = breaks) +
  coord_cartesian(xlim = c(0, 60)) +
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Students Per Presentation: Zoomed into bulk of distribution") + 
  theme(text = element_text(size = 14)) 

ggsave(filename = "Students Per Presentation.png", plot = p, width = 15, height = 7, units = "in") 

p <- 
  qplot(df_sr$num_students, geom="histogram", binwidth = 1) +
  scale_y_continuous(name = "Count", labels = scales::comma) +  # unit_format(unit = "K") +
  scale_x_continuous(name="Number of Students", breaks =c(1:10)) +
  coord_cartesian(xlim = c(0, 10)) +
  theme(panel.grid.minor.y = element_blank()) + 
  theme(panel.background = element_blank()) +
  ggtitle("Students Per Presentation: Zoomed into low numbers") + 
  theme(text = element_text(size = 14)) 

ggsave(filename = "Students Per Presentation (zoomed in small).png", plot = p) 
```


```{r}
# Calculate total code runtime
code_end_time <- Sys.time()
code_runtime <- code_end_time - code_start_time
print(round(code_runtime,1))
```
